# Generated by Django 5.2.6 on 2025-09-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewinghistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='viewinghistory',
            name='article',
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='article_url',
            field=models.URLField(default=''),
        ),
    ]
