# Generated by Django 5.2.6 on 2025-09-23 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_viewinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewinghistory',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.article'),
            preserve_default=False,
        ),
    ]
