# Generated by Django 5.2.6 on 2025-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_viewinghistory_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
